fieldLayouts:
  d8c85013-b461-4a17-8178-4f7b805a5346:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: 'Vul de titel van de pagina in'
            label: Titel
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 19636e41-142e-4501-8e6d-6d15e7c09aff
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: ffcb7357-715a-462b-9baa-51a6a940f889 # Afbeelding hoofding
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 074259d8-7e7a-4169-a052-333657cf05b9
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: b5de6dcf-80e6-48e2-b846-0dab7f35c4c8 # Intro tekst
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6e1f12d7-108f-49d2-a0df-bec6aea1ae19
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d67b49c6-ccb0-4d66-a1dd-9ff1355a0906 # Call To Actions
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 41ea151c-325a-4a28-b9de-49d926855505
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 1992b2db-b8c6-407c-a404-d33fcf58631d
            userCondition: null
          -
            elementCondition: null
            fieldUid: 56d715d0-6a9d-4562-9c66-e5b4caad7f44 # Content builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cbcc6c63-9c29-43c4-8cf0-6747d707f1f0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b1424b4b-17cb-4f44-b72e-63bf261659d9 # Nieuws aan/uit knop
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f45350c3-7040-4950-a3e9-150e326da4b9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 61dd419f-370d-4a3e-9086-d929e3726da1
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4a2bad07-8d89-4689-b0bf-774eed764660 # Overzicht titel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7214630d-01bb-423a-9861-78d2afc49d4a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2f8a6ddc-4ab7-4f9f-a2ea-72c6cb387f38 # Overzicht beschrijving
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 13bfb21b-1834-4101-bbf3-cba3077fd950
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 15ed2b72-8955-4cec-93f8-9736a9e50e80 # Overzicht afbeelding
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 63b30aa3-4961-49e1-b294-383d18e465f5
            userCondition: null
            warning: null
            width: 100
        name: Overview
        uid: 8226ad71-7a1b-40fe-9708-e699b1f0575d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 685530fc-e1f1-4be1-813b-ebf9ac3aa108 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ad72084-5180-4879-a8db-5821c8968a54
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 073a648a-66b3-4bbd-a4df-bc664f69d386
        userCondition: null
handle: about
hasTitleField: true
name: 'Over Vario'
section: 8dd3ea65-76f3-48f6-baf2-5d3c37d61e18 # Over Vario
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
