fieldLayouts:
  5ad79123-ecb1-4dbd-a96a-68b951b58a85:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: 'Vul de titel van de pagina in'
            label: Titel
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3ad016c6-3723-4a61-9c5b-3c5812a1b402
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: ffcb7357-715a-462b-9baa-51a6a940f889 # Afbeelding hoofding
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3dba2827-ac53-406a-a865-a1ace0fb22e3
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: b5de6dcf-80e6-48e2-b846-0dab7f35c4c8 # Intro tekst
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d5cef644-a0f4-487b-bbb2-61ddb390908e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d67b49c6-ccb0-4d66-a1dd-9ff1355a0906 # Call To Actions
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2148ce33-c11b-47ff-bc8c-97bb0da0d8d1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: e88ee46d-b5b8-4b6f-bc7a-ce96b9f11c83
            userCondition: null
          -
            elementCondition: null
            fieldUid: 56d715d0-6a9d-4562-9c66-e5b4caad7f44 # Content builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8d6c81b1-08e5-4bbb-9b3f-bef8f49aec95
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            style: tip
            tip: 'Hieronder verschijnt automatisch het inschrijvingsformulier voor het colloquium'
            type: craft\fieldlayoutelements\Tip
            uid: 9157d131-2be4-4c83-855e-80d91d2957b8
            userCondition: null
        name: Content
        uid: 64aaea23-a880-4a5b-bbd1-d4a3942a2545
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4a2bad07-8d89-4689-b0bf-774eed764660 # Overzicht titel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 869e8ab5-3d47-4fe3-9422-eba3079e6555
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2f8a6ddc-4ab7-4f9f-a2ea-72c6cb387f38 # Overzicht beschrijving
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c31ed558-cf72-4552-b64f-309a280bdee7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 15ed2b72-8955-4cec-93f8-9736a9e50e80 # Overzicht afbeelding
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6fc4d48e-9071-4881-a556-36bc8da924b9
            userCondition: null
            warning: null
            width: 100
        name: Overview
        uid: 2a3f8386-f94c-486c-a653-971f523e2eae
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 685530fc-e1f1-4be1-813b-ebf9ac3aa108 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9994d97c-cc53-4fe6-82fe-d3d9ff316910
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 5fa42ea3-98d4-470b-80bd-f9846837578a
        userCondition: null
handle: colloquium
hasTitleField: true
name: Colloquium
section: f9bf34b7-61cc-440c-a197-0b140eb8d4f2 # Colloquium
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
