fieldLayouts:
  3ae7bc1a-3549-4cf7-b582-b14850d82009:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b529d7c2-b5c0-4b9a-875f-f0c7bed547a8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 37471b2c-6c44-4b1a-bc50-3788e9de05d5 # Hero
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a605f24a-591e-4b94-85f5-47c65857c10c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 783d493c-8241-4ae9-85c8-9fa5536b8fd7
            userCondition: null
          -
            elementCondition: null
            fieldUid: 56d715d0-6a9d-4562-9c66-e5b4caad7f44 # Content builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7562db86-2c1d-47e5-83a3-04f3afc6095e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b1424b4b-17cb-4f44-b72e-63bf261659d9 # Nieuws aan/uit knop
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8e5f6786-be42-49da-95d0-6a93e7cc7127
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1205a3a9-5c1d-4489-8028-3fea6deae86d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4a2bad07-8d89-4689-b0bf-774eed764660 # Overzicht titel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 521e2e8e-23e5-450b-a8b0-174f4c6c38af
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2f8a6ddc-4ab7-4f9f-a2ea-72c6cb387f38 # Overzicht beschrijving
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ff25715e-86d6-40ac-a95b-292c444b508e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 15ed2b72-8955-4cec-93f8-9736a9e50e80 # Overzicht afbeelding
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c8948948-54b9-40f4-9487-55e4f2a3049c
            userCondition: null
            warning: null
            width: 100
        name: Overview
        uid: f60c50d0-0c1a-4327-93ff-90da4a58ee0f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 685530fc-e1f1-4be1-813b-ebf9ac3aa108 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 57127485-addf-441a-b2ab-e79953acbd82
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: d3cabc83-b7a2-4c8f-918c-e02557647516
        userCondition: null
handle: home
hasTitleField: false
name: Home
section: 5611e98d-93ec-4bd4-95dd-18f282b8c5e8 # Home
sortOrder: 1
titleFormat: '{hero.heroTitle|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
