fieldLayouts:
  86c0a01b-0087-45e9-a0e0-cba74925a69a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: 'Vul de titel van de pagina in'
            label: Titel
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: dd5b55f1-b7d2-41d9-93f2-3e8672701671
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: b5de6dcf-80e6-48e2-b846-0dab7f35c4c8 # Intro tekst
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 36c5f86d-a0d6-4a12-a410-872db4f9a8a0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 14aed8a1-6e29-4a27-a210-71930d1d981e
            userCondition: null
          -
            elementCondition: null
            fieldUid: a578ec40-7ca2-4ad8-a25a-a0802af1bd01 # Advies
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4bedbb28-7962-4019-9824-530b32ed2f7d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3d6caa38-c632-4f5c-8a0a-7e2fb79ac0d5 # Externe link
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9232e8b1-be6f-4065-a0f9-98114cce9aa3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9a0ae88e-f7b8-431e-8f19-899dbc2beb8b
        userCondition: null
handle: impact
hasTitleField: true
name: Impact
section: 1a86f1e5-d0ec-40ae-9ab5-b58e891d1ea3 # Impact
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
