defaultPlacement: end
fieldLayouts:
  7ca09cb5-dfea-4173-a601-1bcf64692d26:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 3758f6ee-956f-4f4a-99ff-4924cab0b62f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1c3832dd-0c1e-4b9d-82db-edd51908afe0
        userCondition: null
handle: reportType
name: 'Type Advies'
siteSettings:
  6de046f0-6167-4af1-aa91-ffaf83e36a14: # Vario NL
    hasUrls: false
    template: null
    uriFormat: null
  e57cf13b-f9cb-484a-8093-a897fa43eb68: # EN
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: 78b2b49c-eecb-4537-a468-a35be85a7b1c
