field: 56d715d0-6a9d-4562-9c66-e5b4caad7f44 # Content builder
fieldLayouts:
  9334ab5d-2a5e-48de-8e2b-f9473c1d7ffb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4769bfc3-3064-404b-baa5-1bd5c5ff2acf # Titel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ceea9b40-c972-44ed-9a78-13e297b373d1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9b825b00-aa1c-4ad2-b013-e29ee855e551 # Tekst
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 061635db-57d8-499f-8247-683051ee2000
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 74a30650-eb90-462f-a104-de1d41ac8221 # Formulier
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d82ff4e9-a339-4dc7-993a-33ddbc7770e6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ae73d04c-119e-4cc7-a3fc-bf41d36c5510 # Achtergrondkleur
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ed5937b6-3da0-49f4-a479-17835510d6e3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 93748cb1-718c-4f6b-bf7f-2905cce71126
        userCondition: null
fields:
  9b825b00-aa1c-4ad2-b013-e29ee855e551: # Tekst
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: 'Geef hier een optionele tekst in'
    name: Tekst
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Standard.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
  74a30650-eb90-462f-a104-de1d41ac8221: # Formulier
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: form
    instructions: 'Selecteer een formulier uit onderstaande lijst'
    name: Formulier
    searchable: false
    settings:
      allowSelfRelations: false
      localizeRelations: false
      maxRelations: null
      minRelations: null
      selectionLabel: 'Voeg een formulier toe'
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\formie\fields\Forms
  4769bfc3-3064-404b-baa5-1bd5c5ff2acf: # Titel
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: blockTitle
    instructions: 'Voeg een optionele titel toe boven het formulier'
    name: Titel
    searchable: true
    settings:
      someAttribute: null
    translationKeyFormat: null
    translationMethod: site
    type: modules\statik\fields\AnchorLink
  ae73d04c-119e-4cc7-a3fc-bf41d36c5510: # Achtergrondkleur
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: backgroundColor
    instructions: 'Selecteer de achtergrondkleur van het blok. Belangrijk: Afhankelijk van de achtergrondkleur kan de tekstkleur automatisch mee veranderen.'
    name: Achtergrondkleur
    searchable: false
    settings:
      dataSet: 'Background colors'
      type: dropdown
    translationKeyFormat: null
    translationMethod: none
    type: statikbe\configvaluesfield\fields\ConfigValuesFieldField
handle: form
name: Formulier
sortOrder: 8
