field: 56d715d0-6a9d-4562-9c66-e5b4caad7f44 # Content builder
fieldLayouts:
  dbac7280-eb96-48c9-9218-1f8706af3656:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: cd736fb3-c9b7-4ce1-88a8-da8b64249eb1 # Afbeelding
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: baa9eb81-3124-4edd-8cfd-8a294e0b0c16
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 683cbd88-ef11-45e0-83b4-e20d03f6ea6b # Afbeelding breedte
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a3e4f5ff-7dc0-4e82-b00c-8bea4e6b9b70
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 9abed6d9-3042-4dd4-add0-3115a6e2693b # Afbeelding positie
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5703cb2e-6333-45b2-b5b8-78da1173aca7
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 4ce05044-aa3d-4bbe-ad21-be03fbc1a273 # Achtergrondkleur
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ccae05e3-e8e4-4417-a452-ae31afa6664d
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 9084b802-1468-4763-a867-2e4b1ebd3f09 # Toon een grotere versie van de afbeelding in een popup
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: feb576a2-753f-4c0e-bc99-499d303293d5
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: f986a838-979a-4945-abe0-cd3c6cbad150
        userCondition: null
fields:
  4ce05044-aa3d-4bbe-ad21-be03fbc1a273: # Achtergrondkleur
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: backgroundColor
    instructions: 'Selecteer de achtergrondkleur van het blok. Belangrijk: Afhankelijk van de achtergrondkleur kan de tekstkleur automatisch mee veranderen.'
    name: Achtergrondkleur
    searchable: false
    settings:
      dataSet: 'Background colors'
      type: dropdown
    translationKeyFormat: null
    translationMethod: none
    type: statikbe\configvaluesfield\fields\ConfigValuesFieldField
  9abed6d9-3042-4dd4-add0-3115a6e2693b: # Afbeelding positie
    columnSuffix: vwktiheg
    contentColumnType: string
    fieldGroup: null
    handle: imagePosition
    instructions: 'Selecteer de positie van de afbeelding'
    name: 'Afbeelding positie'
    searchable: false
    settings:
      default: center
      options:
        __assoc__:
          -
            - left
            - '1'
          -
            - center
            - '1'
          -
            - right
            - '1'
          -
            - full
            - ''
          -
            - drop-left
            - ''
          -
            - drop-right
            - ''
    translationKeyFormat: null
    translationMethod: none
    type: rias\positionfieldtype\fields\Position
  683cbd88-ef11-45e0-83b4-e20d03f6ea6b: # Afbeelding breedte
    columnSuffix: xbqglaie
    contentColumnType: string
    fieldGroup: null
    handle: imageWidth
    instructions: 'Selecteer de gewenste breedte van de afbeelding'
    name: 'Afbeelding breedte'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - full
            -
              - value
              - full
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 1/2
            -
              - value
              - half
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 1/3
            -
              - value
              - oneThird
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 1/4
            -
              - value
              - oneFourth
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  9084b802-1468-4763-a867-2e4b1ebd3f09: # Toon een grotere versie van de afbeelding in een popup
    columnSuffix: xmzvkqux
    contentColumnType: boolean
    fieldGroup: null
    handle: showLargerVersionInPopup
    instructions: null
    name: 'Toon een grotere versie van de afbeelding in een popup'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  cd736fb3-c9b7-4ce1-88a8-da8b64249eb1: # Afbeelding
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: 'De minimale breedte voor deze afbeelding is 1200px. De ideale breedte is 2400px.'
    name: Afbeelding
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: false
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:979c3eeb-f99a-4ca1-bcbe-ce9298a4e4ca' # Files
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:979c3eeb-f99a-4ca1-bcbe-ce9298a4e4ca' # Files
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Voeg een afbeelding toe'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: image
name: Afbeelding
sortOrder: 3
