field: 56d715d0-6a9d-4562-9c66-e5b4caad7f44 # Content builder
fieldLayouts:
  0b203f95-b680-4192-8ebc-fd84ef05fc3c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e6665f06-bacd-4421-bd2e-cdf693c23eaf # Titel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f7c5b6c1-2df2-47a9-9590-8e8c57d48212
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 776fa716-10bb-48bb-ae08-28870f9d77e7 # Entries
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 76be8a95-7f6d-46e0-a7ad-0105ea2dc848
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4389ba83-8e69-4edb-b3c3-ca0ba89617c1 # Achtergrondkleur
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3879b5f6-1d82-4b0d-a1ed-389e9ada1de2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 17a9de58-71d7-452f-a480-1439982cf48e
        userCondition: null
fields:
  776fa716-10bb-48bb-ae08-28870f9d77e7: # Entries
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: entries
    instructions: 'Selecteer de entries (of pagina''s) die je in dit overzicht wil tonen'
    name: Entries
    searchable: true
    settings:
      allowSelfRelations: false
      localizeRelations: true
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: 'Voeg een entry toe'
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  4389ba83-8e69-4edb-b3c3-ca0ba89617c1: # Achtergrondkleur
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: backgroundColor
    instructions: 'Selecteer de achtergrondkleur van het blok. Belangrijk: Afhankelijk van de achtergrondkleur kan de tekstkleur automatisch mee veranderen.'
    name: Achtergrondkleur
    searchable: false
    settings:
      dataSet: 'Background colors'
      type: dropdown
    translationKeyFormat: null
    translationMethod: none
    type: statikbe\configvaluesfield\fields\ConfigValuesFieldField
  e6665f06-bacd-4421-bd2e-cdf693c23eaf: # Titel
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: blockTitle
    instructions: 'Voeg een optionele titel toe aan het blok'
    name: Titel
    searchable: true
    settings:
      someAttribute: null
    translationKeyFormat: null
    translationMethod: site
    type: modules\statik\fields\AnchorLink
handle: overview
name: Overzicht
sortOrder: 9
