field: 56d715d0-6a9d-4562-9c66-e5b4caad7f44 # Content builder
fieldLayouts:
  8e0153f8-35f6-4a49-bc77-316bc5dce081:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 24983cba-9d55-413d-80dc-0374abd19ec0 # Titel kolom 1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e1e3e29f-0360-4cf5-9e9c-185e52b35ec3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b1cd3558-d939-48d0-8628-239236ff699c # Tekst kolom 1
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8066edd1-fae1-4876-b905-cecb2c112d8a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bde7c3e4-1530-4cdf-94a4-6ac068e88c8a # CTA kolom 1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a27db994-44cd-49ce-9e65-16ce6ec8334a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e73dd38a-5d76-40ba-99eb-25ee65bf7ab5 # Titel kolom 2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 12b922f4-dd7e-425b-a3ba-137fc623d829
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a2d7684e-6737-4123-ad14-2c4e4221bbdd # Tekst kolom 2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 59368b27-46f3-4c5b-93b7-9e5bf5641ce9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 84a6a70f-85ce-43a5-ad74-738a0cbea388 # CTA kolom 2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3461e881-b526-426b-be4a-727375056942
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3e5318bd-23e0-4319-8f7c-3f38350d8764 # Achtergrondkleur
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5c08b825-8341-4ca0-a415-67be5bbd04ae
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6a9d5fcb-7371-45df-b9f8-0a603830f3a3
        userCondition: null
fields:
  3e5318bd-23e0-4319-8f7c-3f38350d8764: # Achtergrondkleur
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: backgroundColor
    instructions: 'Selecteer de achtergrondkleur van het blok. Belangrijk: Afhankelijk van de achtergrondkleur kan de tekstkleur automatisch mee veranderen.'
    name: Achtergrondkleur
    searchable: false
    settings:
      dataSet: 'Background colors'
      type: dropdown
    translationKeyFormat: null
    translationMethod: none
    type: statikbe\configvaluesfield\fields\ConfigValuesFieldField
  84a6a70f-85ce-43a5-ad74-738a0cbea388: # CTA kolom 2
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: ctaColumn2
    instructions: 'Voeg een call to action toe, vul een entry of link in en kies de styling (knop of link)'
    name: 'CTA kolom 2'
    searchable: true
    settings:
      allowClass: '1'
      allowCustomText: '1'
      allowTarget: '1'
      allowedLinkNames:
        1: asset
        3: entry
        4: email
        6: url
      class: null
      classes: null
      defaultLinkName: entry
      defaultText: 'Meer lezen'
      typeSettings:
        __assoc__:
          -
            - asset
            -
              __assoc__:
                -
                  - sources
                  - '*'
          -
            - category
            -
              __assoc__:
                -
                  - sources
                  - '*'
          -
            - entry
            -
              __assoc__:
                -
                  - sources
                  - '*'
          -
            - email
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
          -
            - tel
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
          -
            - url
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
    translationKeyFormat: null
    translationMethod: site
    type: statikbe\cta\fields\CTAField
  24983cba-9d55-413d-80dc-0374abd19ec0: # Titel kolom 1
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: titleColumn1
    instructions: 'Voeg een optionele titel toe aan de eerste kolom van het blok'
    name: 'Titel kolom 1'
    searchable: true
    settings:
      someAttribute: null
    translationKeyFormat: null
    translationMethod: site
    type: modules\statik\fields\AnchorLink
  a2d7684e-6737-4123-ad14-2c4e4221bbdd: # Tekst kolom 2
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: textColumn2
    instructions: 'Geef hier de tekst in van de tweede kolom'
    name: 'Tekst kolom 2'
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Extended.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
  b1cd3558-d939-48d0-8628-239236ff699c: # Tekst kolom 1
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: textColumn1
    instructions: 'Geef hier de tekst in van de eerste kolom'
    name: 'Tekst kolom 1'
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Extended.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
  bde7c3e4-1530-4cdf-94a4-6ac068e88c8a: # CTA kolom 1
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: ctaColumn1
    instructions: 'Voeg een call to action toe, vul een entry of link in en kies de styling (knop of link)'
    name: 'CTA kolom 1'
    searchable: true
    settings:
      allowClass: '1'
      allowCustomText: '1'
      allowTarget: '1'
      allowedLinkNames:
        1: asset
        3: entry
        4: email
        6: url
      class: null
      classes: null
      defaultLinkName: entry
      defaultText: 'Meer lezen'
      typeSettings:
        __assoc__:
          -
            - asset
            -
              __assoc__:
                -
                  - sources
                  - '*'
          -
            - category
            -
              __assoc__:
                -
                  - sources
                  - '*'
          -
            - entry
            -
              __assoc__:
                -
                  - sources
                  - '*'
          -
            - email
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
          -
            - tel
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
          -
            - url
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
    translationKeyFormat: null
    translationMethod: site
    type: statikbe\cta\fields\CTAField
  e73dd38a-5d76-40ba-99eb-25ee65bf7ab5: # Titel kolom 2
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: titleColumn2
    instructions: 'Voeg een optionele titel toe aan de tweede kolom van het blok'
    name: 'Titel kolom 2'
    searchable: true
    settings:
      someAttribute: null
    translationKeyFormat: null
    translationMethod: site
    type: modules\statik\fields\AnchorLink
handle: textTwoColumns
name: 'Tekst (2 kolommen)'
sortOrder: 2
