fieldLayouts:
  a646a8f4-7495-4add-979c-80f88cae05f0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a44287f8-d6ed-4f2c-8a63-0c1312ef236e # Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a6b3c8ef-0a56-4a1a-9941-e7795e93ef30
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 01236916-9df1-42d8-9cd9-9169ed3294d1
        userCondition: null
handle: fallback
name: Fallback
sortOrder: 1
