fieldLayouts:
  6f7fef0a-6de7-486f-887d-716ee0d2a256:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f694fce1-48ca-4bfe-9fba-196195547a36 # Facebook
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eaf16c77-8fa3-4077-9421-d519d42277eb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2e4b3bb0-26e4-47d2-9445-54401a221c63 # Twitter
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ed2a7a63-ee62-4397-82db-0d40a38331a6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ce1fab3c-0b02-49d8-8d8f-1bab2d7c05e2 # LinkedIn
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bea39c47-1f47-458d-9db2-ddf143321eef
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9bc4b9f2-7fc6-48b0-a3df-8e9c061a70c6 # Instagram
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 340bce2c-57ce-47fc-a9fc-d7d3f2e06fda
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6221c006-75b9-4fa5-a352-4cd4317fb5d7 # Youtube
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a7f9e68a-979a-4dff-b452-8f1b1ded95fd
            userCondition: null
            warning: null
            width: 100
        name: 'Social links'
        uid: eae9a06c-bf89-49cc-b749-3752282019d1
        userCondition: null
handle: socialMedia
name: 'Social Media'
sortOrder: 4
