changedFieldIndicator: 434909910
field: 9faf6a00-afea-4a29-a217-e6af774f6b55 # Call to action
fieldLayouts:
  77473d9a-25e1-402f-a763-c6e3ff92bdbb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: fc9b3c7f-00f8-4113-aa56-b2328011d192 # Link
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0560c026-0cac-404b-befd-dea57fbbf76a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 19e54462-5c5c-4f5f-bd0e-e072e2830190
        userCondition: null
fields:
  fc9b3c7f-00f8-4113-aa56-b2328011d192: # Link
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: linkit
    instructions: null
    name: Link
    searchable: true
    settings:
      allowClass: '1'
      allowCustomText: '1'
      allowTarget: '1'
      allowedLinkNames:
        1: asset
        3: entry
        4: email
        6: url
      class: null
      classes: null
      defaultLinkName: entry
      defaultText: 'Meer lezen'
      typeSettings:
        __assoc__:
          -
            - asset
            -
              __assoc__:
                -
                  - sources
                  - '*'
          -
            - category
            -
              __assoc__:
                -
                  - sources
                  - '*'
          -
            - entry
            -
              __assoc__:
                -
                  - sources
                  - '*'
          -
            - email
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
          -
            - tel
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
          -
            - url
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
    translationKeyFormat: null
    translationMethod: site
    type: statikbe\cta\fields\CTAField
