changedFieldIndicator: 2145933910
field: 302aeb89-2e5c-42f2-a735-98e504b28a37 # Call to action
fieldLayouts:
  d85d743d-9445-4bbe-b507-717c93f5ba87:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6d99d3e8-e687-44e6-9e4f-8724da1c5123 # Link
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f193109f-69bc-48cc-bc5e-fe47668348ab
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 40118460-76f4-4e75-a990-501af0e7e2e8
        userCondition: null
fields:
  6d99d3e8-e687-44e6-9e4f-8724da1c5123: # Link
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: linkit
    instructions: null
    name: Link
    searchable: true
    settings:
      allowClass: '1'
      allowCustomText: '1'
      allowTarget: '1'
      allowedLinkNames:
        1: asset
        3: entry
        4: email
        6: url
      class: null
      classes: null
      defaultLinkName: entry
      defaultText: 'Meer lezen'
      typeSettings:
        __assoc__:
          -
            - asset
            -
              __assoc__:
                -
                  - sources
                  - '*'
          -
            - category
            -
              __assoc__:
                -
                  - sources
                  - '*'
          -
            - entry
            -
              __assoc__:
                -
                  - sources
                  - '*'
          -
            - email
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
          -
            - tel
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
          -
            - url
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
    translationKeyFormat: null
    translationMethod: site
    type: statikbe\cta\fields\CTAField
