changedFieldIndicator: null
field: 811394e0-7634-4f3e-a74f-b59e35e18fee # Nieuwsbrief CTA
fieldLayouts:
  3a7e719a-21ee-47f2-8a34-ff725697a5c1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 063c0983-8106-4412-a2c4-d55211370e04 # Titel
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1e57d71a-940b-442d-981a-6f468afd3c7e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 50da4649-b0bc-47d4-8f98-24ab08443b4f # Tekst
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f29a55b4-85d0-436a-925b-f39357988acb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5769c4a7-6939-40b1-8feb-5675564a8e99 # Link
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 95321f60-c564-4ed7-a87a-2e103a73208f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 04426bf9-22d2-438d-8f61-85fcae920a95
        userCondition: null
fields:
  50da4649-b0bc-47d4-8f98-24ab08443b4f: # Tekst
    columnSuffix: ubriqzbh
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Tekst
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Simple.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
  063c0983-8106-4412-a2c4-d55211370e04: # Titel
    columnSuffix: vrhlqxot
    contentColumnType: text
    fieldGroup: null
    handle: blockTitle
    instructions: null
    name: Titel
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  5769c4a7-6939-40b1-8feb-5675564a8e99: # Link
    columnSuffix: fiwscsic
    contentColumnType: text
    fieldGroup: null
    handle: linkit
    instructions: 'Link naar een Asset (afbeelding/document), Entry, e-mailadres of (externe) url. Het is ook mogelijk de stijl van de knop/link te kiezen.'
    name: Link
    searchable: false
    settings:
      allowClass: '1'
      allowCustomText: '1'
      allowTarget: '1'
      allowedLinkNames:
        1: asset
        3: entry
        4: email
        6: url
      class: null
      classes: null
      defaultLinkName: entry
      defaultText: ''
      typeSettings:
        __assoc__:
          -
            - asset
            -
              __assoc__:
                -
                  - sources
                  - '*'
          -
            - category
            -
              __assoc__:
                -
                  - sources
                  - '*'
          -
            - entry
            -
              __assoc__:
                -
                  - sources
                  - '*'
          -
            - email
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
          -
            - tel
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
          -
            - url
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
    translationKeyFormat: null
    translationMethod: site
    type: statikbe\cta\fields\CTAField
