changedFieldIndicator: null
field: 7d7ac2ae-38ea-488e-b5bb-926fdda4aaf6 # 1 kolom met foto
fieldLayouts:
  dd6cbb70-f379-4e13-a879-2b06ed962987:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 1319d4b9-dade-4a26-b68b-0afd3da6d26a # Tekst
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: af734789-4fed-483c-96bd-963cf2b92827
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d3ce3a4f-d766-4346-b38d-e2482ad644bb # Afbeelding
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0bc2163a-75f3-44cc-b8c4-743c0f594aa9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 74771a8c-8821-4335-a363-8cc8abe834a5
        userCondition: null
fields:
  1319d4b9-dade-4a26-b68b-0afd3da6d26a: # Tekst
    columnSuffix: lvvuzrth
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: 'Geef hier de tekst in'
    name: Tekst
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Extended.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
  d3ce3a4f-d766-4346-b38d-e2482ad644bb: # Afbeelding
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: 'De minimale breedte voor deze afbeelding is 660px. De ideale breedte is 1320px.'
    name: Afbeelding
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:979c3eeb-f99a-4ca1-bcbe-ce9298a4e4ca' # Files
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:979c3eeb-f99a-4ca1-bcbe-ce9298a4e4ca' # Files
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Kies een afbeelding'
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
