defaultPlacement: end
enableVersioning: true
handle: about
name: 'Over Vario'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  6de046f0-6167-4af1-aa91-ffaf83e36a14: # Vario NL
    enabledByDefault: true
    hasUrls: true
    template: _site/_about.twig
    uriFormat: over-ons
  e57cf13b-f9cb-484a-8093-a897fa43eb68: # EN
    enabledByDefault: true
    hasUrls: true
    template: _site/_about.twig
    uriFormat: about-us
type: single
