columnSuffix: null
contentColumnType: string
fieldGroup: 2c770290-8edc-4f26-b846-6d99d36d7844 # Common
handle: callToActions
instructions: null
name: 'Call To Actions'
searchable: false
settings:
  blockTypeFields: 0
  changedFieldIndicator: 2019877280
  contentTable: '{{%stc_calltoactions}}'
  fieldLayout: matrix
  maxRows: null
  minRows: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: 'Voeg een link toe'
  staticField: null
translationKeyFormat: null
translationMethod: none
type: verbb\supertable\fields\SuperTableField
