columnSuffix: null
contentColumnType: string
fieldGroup: 2c770290-8edc-4f26-b846-6d99d36d7844 # Common
handle: contentBuilder
instructions: 'Bouw de pagina op met blokken naar jullie keuze en geef de content in'
name: 'Content builder'
searchable: true
settings:
  contentTable: '{{%matrixcontent_contentbuilder}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: none
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
