columnSuffix: null
contentColumnType: string(255)
fieldGroup: 39b3406d-d1bb-4a84-a13a-bce5cc293238 # Globals
handle: instagram
instructions: null
name: Instagram
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
