columnSuffix: null
contentColumnType: text
fieldGroup: e9218327-8360-4a72-aae4-ff2db8be2c18 # Overview
handle: overviewTitle
instructions: 'Vul een titel in die in overzichtsblokjes op andere pagina''s getoond zal worden'
name: 'Overzicht titel'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
