columnSuffix: null
contentColumnType: text
fieldGroup: e9218327-8360-4a72-aae4-ff2db8be2c18 # Overview
handle: overviewDescription
instructions: 'Vul de tekst in die in overzichtsblokjes op andere pagina''s getoond zal worden. Dit mag een heel kort aansprekend tekstje zijn.'
name: 'Overzicht beschrijving'
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: '*'
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: null
  purifyHtml: true
  redactorConfig: Simple.json
  removeEmptyTags: true
  removeInlineStyles: true
  removeNbsp: true
  showHtmlButtonForNonAdmins: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: enlarged
translationKeyFormat: null
translationMethod: site
type: craft\redactor\Field
